### PR TITLE
Make odom child frame parameterizable + some CMake

### PR DESCRIPTION
**Pull request by jmirabel**
The install path change is related to https://github.com/stack-of-tasks/dynamic_graph_bridge/commit/576bf36e13bea387f27a275d3dfbd0f1755fc19b#r38313060

### CODE REVIEW

**Comment by jmirabel** [comment]
Please, don't merge as this is WIP.

**Comment by jmirabel** [comment]
This is not WIP anymore.

**Comment by jmirabel** [comment]
On packages that depends on this one, I now have
```
CMake Error at /home/jmirabel/devel/agimus/install/lib/cmake/dynamic_graph_bridge/dynamic_graph_bridgeTargets.cmake:132 (message):
  The imported target "dynamic_graph_bridge::geometric_simu" references the
  file

     "/home/jmirabel/devel/agimus/install/bin/geometric_simu"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/home/jmirabel/devel/agimus/install/lib/cmake/dynamic_graph_bridge/dynamic_graph_bridgeTargets.cmake"

  but not all the files it references.
```
@nim65s  Do you know how to fix that ?

**Comment by nim65s** [comment]
In dynamic_graph_bridgeTargets.cmake I have:
```
# Create imported target dynamic_graph_bridge::geometric_simu
add_executable(dynamic_graph_bridge::geometric_simu IMPORTED)
```

Looking at the [doc](https://cmake.org/cmake/help/latest/command/add_executable.html), I guess we have to specify the `IMPORTED_LOCATION` for this target.

But do you know why ROS wants the binaries to go to `share` instead of `bin` ?

**Comment by jmirabel** [comment]
> Looking at the [doc](https://cmake.org/cmake/help/latest/command/add_executable.html), I guess we have to specify the `IMPORTED_LOCATION` for this target.

I tried but couldn't get this to work.

> But do you know why ROS wants the binaries to go to `share` instead of `bin` ?

I think by default, the binaries are installed in `lib/package/...` but it is also possible to install them in share. I think they do this because they want users to launch them using rosrun. In our case, launch geometric_simu outside ROS does not make much sense. I don't even know if it works.

**Comment by jmirabel** [comment]
@nim65s At the moment, the target geometric_simu isn't used outside of the project. Do you mind if I remove the export and leave it to you to make the export work ? i can open an issue to leave a reminder.

**Comment by nim65s** [comment]
Sure

**Comment by nim65s** [comment]
You will just have to provid a way to reproduce your issue :)

**Comment by olivier-stasse** [comment]
In ROS a binary executable_name is suppose to go in :
```
lib/package_name/extecutable_name
```

**Comment by jmirabel** [comment]
> ```
> 
> ```
> 
> 
> To make it available outside the ROS real, I either copy or create a link to binary  in:
> 
> ```
> ${CMAKE_INSTALL_PREFIX}/bin
> ```

This does not make sense for *geometric_simu*

**Comment by jmirabel** [comment]
I updated the PR accordingly and opened https://github.com/stack-of-tasks/dynamic_graph_bridge/issues/70, though I don't think we should care about exporting executables.

**Comment by nim65s** [comment]
I don't think we should care about anything as long as it's not required. And here, the export is not required for anything (yet).

But for the sport, I'd like to understand how to solve #70 :)

**Comment by olivier-stasse** [comment]
Out of curiosity: was the export creating a bug ?

**Comment by jmirabel** [comment]
> Out of curiosity: was the export creating a bug ?

Have a look at #70.

**Pull request merged**
